// <auto-generated />
using Dentisterie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetworkSimulation.Migrations
{
    [DbContext(typeof(ReseauDbContext))]
    partial class ReseauDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetworkSimulation.Entities.Serveur", b =>
                {
                    b.Property<int>("id_serveur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_serveur"));

                    b.Property<bool>("activite")
                        .HasColumnType("boolean");

                    b.Property<string>("ip_adress")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("x")
                        .HasColumnType("integer");

                    b.Property<int>("y")
                        .HasColumnType("integer");

                    b.HasKey("id_serveur");

                    b.ToTable("serveurs");
                });

            modelBuilder.Entity("NetworkSimulation.Entities.UrlMapping", b =>
                {
                    b.Property<int>("id_mapping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_mapping"));

                    b.Property<int>("id_serveur")
                        .HasColumnType("integer");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_mapping");

                    b.HasIndex("id_serveur");

                    b.ToTable("dns");
                });

            modelBuilder.Entity("NetworkSimulation.Entities.UrlMapping", b =>
                {
                    b.HasOne("NetworkSimulation.Entities.Serveur", "serveur")
                        .WithMany("urls")
                        .HasForeignKey("id_serveur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("serveur");
                });

            modelBuilder.Entity("NetworkSimulation.Entities.Serveur", b =>
                {
                    b.Navigation("urls");
                });
#pragma warning restore 612, 618
        }
    }
}
